---
- hosts: all
  become: yes

  tasks:
    - name: Update EC2
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install pip
      apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 3600
        state: present

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Run app.py
      command: python app.py
